name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install only the root dependencies, excluding api folder
      - name: Install dependencies
        run: npm ci --ignore-scripts
        working-directory: .

      # Build only the Next.js app
      - name: Build
        run: npm run build
        working-directory: .
        env:
          # Prevent TypeScript from checking the api directory
          SKIP_API_TYPES: true
          NEXT_PUBLIC_CRON_SECRET: ${{ secrets.CRON_SECRET }}
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2